"""add nullable fields

Revision ID: 0dea8d89870a
Revises: 38280687175f
Create Date: 2022-04-12 16:39:57.354537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dea8d89870a'
down_revision = '38280687175f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books_prices', 'shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('books_prices', 'book_slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('shops_books', 'shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shops_books', 'book_slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shops_books', 'book_slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shops_books', 'shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books_prices', 'book_slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books_prices', 'shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
