"""add new models

Revision ID: 38280687175f
Revises: f644f2edd7bf
Create Date: 2022-03-30 18:27:26.766233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38280687175f'
down_revision = 'f644f2edd7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('slug', sa.String(), nullable=False))
    op.create_primary_key('pk_isbn', 'books', ['slug'])
    op.drop_index('ix_books_isbn', table_name='books')
    op.create_index(op.f('ix_books_slug'), 'books', ['slug'], unique=False)
    op.drop_column('books', 'isbn')

    op.create_table('books_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('discount_price', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('book_slug', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_slug'], ['books.slug'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_prices_book_slug'), 'books_prices', ['book_slug'], unique=False)
    op.create_index(op.f('ix_books_prices_shop_id'), 'books_prices', ['shop_id'], unique=False)

    op.create_table('shops_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('book_slug', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['book_slug'], ['books.slug'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_books_book_slug'), 'shops_books', ['book_slug'], unique=False)
    op.create_index(op.f('ix_shops_books_shop_id'), 'shops_books', ['shop_id'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_books_slug'), table_name='books')
    op.create_index('ix_books_isbn', 'books', ['isbn'], unique=False)
    op.drop_column('books', 'slug')
    op.drop_index(op.f('ix_shops_books_shop_id'), table_name='shops_books')
    op.drop_index(op.f('ix_shops_books_book_slug'), table_name='shops_books')
    op.drop_table('shops_books')
    op.drop_index(op.f('ix_books_prices_shop_id'), table_name='books_prices')
    op.drop_index(op.f('ix_books_prices_book_slug'), table_name='books_prices')
    op.drop_table('books_prices')
    # ### end Alembic commands ###
