"""inital

Revision ID: 4d4ec38cfbee
Revises: 
Create Date: 2022-05-13 11:01:36.763671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4ec38cfbee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('count_pages', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_index(op.f('ix_books_slug'), 'books', ['slug'], unique=False)
    op.create_table('books_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('discount_price', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('book_slug', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_prices_book_slug'), 'books_prices', ['book_slug'], unique=False)
    op.create_index(op.f('ix_books_prices_shop_id'), 'books_prices', ['shop_id'], unique=False)
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_id'), 'shops', ['id'], unique=False)
    op.create_table('shops_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('book_slug', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_books_book_slug'), 'shops_books', ['book_slug'], unique=False)
    op.create_index(op.f('ix_shops_books_shop_id'), 'shops_books', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shops_books_shop_id'), table_name='shops_books')
    op.drop_index(op.f('ix_shops_books_book_slug'), table_name='shops_books')
    op.drop_table('shops_books')
    op.drop_index(op.f('ix_shops_id'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_books_prices_shop_id'), table_name='books_prices')
    op.drop_index(op.f('ix_books_prices_book_slug'), table_name='books_prices')
    op.drop_table('books_prices')
    op.drop_index(op.f('ix_books_slug'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
