"""inital v3

Revision ID: ee5eb1c9fcbb
Revises: 4d4ec38cfbee
Create Date: 2022-05-13 11:02:34.451969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee5eb1c9fcbb'
down_revision = '4d4ec38cfbee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
