"""edit models

Revision ID: f644f2edd7bf
Revises: e050b30d4480
Create Date: 2022-03-30 16:00:57.522858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f644f2edd7bf'
down_revision = 'e050b30d4480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_id'), 'shops', ['id'], unique=False)
    op.drop_index('ix_books_id', table_name='books')
    op.drop_column('books', 'id')
    op.add_column('books', sa.Column('isbn', sa.String(), nullable=False))
    op.add_column('books', sa.Column('count_pages', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('size', sa.String(), nullable=True))
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.create_index('ix_books_id', 'books', ['id'], unique=False)
    op.drop_column('books', 'size')
    op.drop_column('books', 'weight')
    op.drop_column('books', 'count_pages')
    op.drop_column('books', 'isbn')
    op.drop_index(op.f('ix_shops_id'), table_name='shops')
    op.drop_table('shops')
    # ### end Alembic commands ###
