"""inital v4

Revision ID: fc7c0699febe
Revises: ee5eb1c9fcbb
Create Date: 2022-05-13 11:47:51.637820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc7c0699febe'
down_revision = 'ee5eb1c9fcbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'books_prices', ['shop_id', 'book_slug', 'date'])
    op.create_foreign_key(None, 'books_prices', 'shops', ['shop_id'], ['id'])
    op.create_foreign_key(None, 'books_prices', 'books', ['book_slug'], ['slug'])
    op.create_unique_constraint(None, 'shops_books', ['shop_id', 'book_slug'])
    op.create_foreign_key(None, 'shops_books', 'shops', ['shop_id'], ['id'])
    op.create_foreign_key(None, 'shops_books', 'books', ['book_slug'], ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops_books', type_='foreignkey')
    op.drop_constraint(None, 'shops_books', type_='foreignkey')
    op.drop_constraint(None, 'shops_books', type_='unique')
    op.drop_constraint(None, 'books_prices', type_='foreignkey')
    op.drop_constraint(None, 'books_prices', type_='foreignkey')
    op.drop_constraint(None, 'books_prices', type_='unique')
    # ### end Alembic commands ###
